version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis
    volumes:
      - redis-data:/data
  microservice-ex:
    image: josmbrio/microservice-ex:py-1.0
    ports:
      - 5000:5000
#    environment:
    container_name: microservice-ex
    depends_on:
      - redis
volumes:
  redis-data:
    driver: local
