apiVersion: apps/v1
kind: Deployment
metadata:
    name: $APP_NAME
    namespace: ex-microservices
    labels:
        app: $APP_NAME
spec:
    replicas: 2
    selector:
        matchLabels:
            app: $APP_NAME
    template:
        metadata:
            labels:
                app: $APP_NAME
        spec:
            containers:
                - name: $APP_NAME
                  image: $IMAGE_TAG
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 9000
                  env:
                    - name: REDIS_HOST
                      valueFrom:
                        configMapKeyRef:
                          name: redis
                          key: HOST
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
    namespace: ex-microservices
    labels:
        app: redis
spec:
    selector:
        matchLabels:
            app: redis
    template:
        metadata:
            labels:
                app: redis
        spec:
            imagePullSecrets:
                - name: docker-registry
            containers:
                - name: redis
                  image: redis
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 6379