apiVersion: v1
data:
  HOST: $REDIS_HOST
kind: ConfigMap
metadata:
  name: redis
  namespace: $APP_NAMESPACE
---
apiVersion: v1
kind: Service
metadata:
    name: $APP_NAME
    namespace: $APP_NAMESPACE
spec:
    selector:
        app: $APP_NAME
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: $APP_NAME
    namespace: $APP_NAMESPACE
    labels:
        app: $APP_NAME
spec:
    replicas: 2
    selector:
        matchLabels:
            app: $APP_NAME
    template:
        metadata:
            labels:
                app: $APP_NAME
        spec:
            containers:
                - name: $APP_NAME
                  image: $IMAGE_TAG
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 9000
                  env:
                    - name: REDIS_HOST
                      valueFrom:
                        configMapKeyRef:
                          name: redis
                          key: HOST