apiVersion: v1
kind: Service
metadata:
    name: redis
    namespace: ex-microservices
spec:
    selector:
        app: redis
    ports:
        - protocol: TCP
          port: 6379
          targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
    namespace: ex-microservices
    labels:
        app: redis
spec:
    selector:
        matchLabels:
            app: redis
    template:
        metadata:
            labels:
                app: redis
        spec:
            imagePullSecrets:
                - name: docker-registry
            containers:
                - name: redis
                  image: redis
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 6379