apiVersion: v1
kind: Service
metadata:
    name: $APP_NAME
    namespace: ex-microservices
spec:
    selector:
        app: $APP_NAME
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 9000
          targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
    name: redis
    namespace: ex-microservices
spec:
    selector:
        app: redis
    ports:
        - protocol: TCP
          port: 6379
          targetPort: 6379